### ISSUE TITLE
Midpoint Demo Feedback

### ISSUE THREAD

**Issue by jbwoo9779** [StanfordCS194/Team-4#5]
Hi Scribe.

Attached is feedback from the peer to peer feedback form. I also included the average scores students rated your demo on Engagement, Creativity, and Execution. These are not evaluative, but instead a metric to gauge other teams' perception of your progress.

By the end of the weekend, I will send an email detailing the teaching team's specific feedback. Until then, keep on developing.

| Engagement  | Creativity | Execution |
| ------------- | ---------- | ---------- |
| 4.44444444 | 4.11111111 | 4.33333333 |

| Open Ended Feedback  |
| ----------------------- |
| Maybe add more punctuation and voice parsing (so that it is more of a transcript rather than just a bunch of the words all on one line) |
| Really cool!! And very useful. Would be cool if you could separate the different voices / callers. Impressive work though |
| Great great idea, looks like team is on the right track to executing well |
| Really cool idea and seems like you have a lot of cool places to take it as well |
| As someone who has been in many conferences - great tool idea. A lot of utility. |
| Really cool idea, seems useful in a variety of situations. It would be cool if it was labeled which person was speaking at different points. Are you guys planning on distributing only transcriptions or saving audio files are well? Could be useful depending on user disabilities, for example |
| Really useful and cool idea, interface could probably be fleshed out to show transcript of convo along the way on the screen. |
| Seems useful! The audio is super clear which is awesome. I know there are other services that allow you to record calls, so it could be useful to also have a feature that lets you submit a recording and get a transcript. I could also think it would be cool to have a way to really access past transcripts. |
| This is a very interesting project and a very relevant problem. I am excited to see this team applying cutting edge technology. However, they will need to tune their NLP system over the next few weeks. |

**Comment by jsinge97** [comment]
Awesome, thanks @jbwoo9779
